name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: uv syncing
        run: |
          uv sync

      - name: Test help flag (local install)
        run: uv run mav --help

      - name: Test all flags (local install)
        run: | 
          uv run mav \
              --model gpt2 \
              --prompt "Testing MAV tool" \
              --max-new-tokens 5 \
              --aggregation l2 \
              --refresh-rate 0.1 \
              --device cpu \
              --scale linear \
              --limit-chars 200 \
              --temp 0.7 \
              --top-k 40 \
              --top-p 0.9 \
              --min-p 0.1 \
              --repetition-penalty 1.2 \
              --backend transformers \
              --seed 123

      - name: Run MAV script plain (local install)
        run: uv run mav --max-new-tokens 10

      - name: Run Smoke Test - test_first_step.py
        run: uv run examples/test_first_step.py

      - name: Run Smoke Test - test_plugin_fire_entropy.py
        run: uv run examples/test_plugin_fire_entropy.py
      
      - name: Run Smoke Test - test_plugin_random.py
        run: uv run examples/test_plugin_random.py
      
      - name: Run Smoke Test - test_vis_train_loop.py
        run: uv run examples/test_vis_train_loop.py
      
