name: Test MAV Script

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest-gpu  # Use the appropriate GPU runner label

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118  # Adjust CUDA version as needed

      - name: Verify CUDA installation
        run: |
          nvidia-smi
          python -c "import torch; print('CUDA Available:', torch.cuda.is_available())"

      - name: Run MAV script
        run: mav
