name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Get branch name
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

      - name: Install dependencies (local)
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Test help flag (local install)
        run: mav --help

      - name: Test all flags (local install)
        run: | 
          mav \
              --model gpt2 \
              --prompt "Testing MAV tool" \
              --max-new-tokens 5 \
              --aggregation l2 \
              --refresh-rate 0.1 \
              --device cpu \
              --scale linear \
              --limit-chars 200 \
              --temp 0.7 \
              --top-k 40 \
              --top-p 0.9 \
              --min-p 0.1 \
              --repetition-penalty 1.2 \
              --backend transformers \
              --seed 123

      - name: Run MAV script plain (local install)
        run: mav --max-new-tokens 10

      - name: Create new virtual environment for branch install
        run: python -m venv branch_env

      - name: Activate virtual environment and install from PR branch
        run: |
          source branch_env/bin/activate
          python -m pip install --upgrade pip
          pip install git+https://github.com/attentionmech/mav@${BRANCH_NAME}

      - name: Test help flag (branch install)
        run: |
          source branch_env/bin/activate
          mav --help

      - name: Test all flags (branch install)
        run: | 
          source branch_env/bin/activate
          mav \
              --model gpt2 \
              --prompt "Testing MAV tool" \
              --max-new-tokens 5 \
              --aggregation l2 \
              --refresh-rate 0.1 \
              --device cpu \
              --scale linear \
              --limit-chars 200 \
              --temp 0.7 \
              --top-k 40 \
              --top-p 0.9 \
              --min-p 0.1 \
              --repetition-penalty 1.2 \
              --backend transformers \
              --seed 123

      - name: Run MAV script plain (branch install)
        run: |
          source branch_env/bin/activate
          mav --max-new-tokens 10
